name: rangeuniverse
description: "A platform that enables people to excel in tech, whether through learning digital skills or building digital products that make our lives easier and better."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_sign_in: ^6.2.1
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/brand.png
    - assets/images/globalization.jpg
    - assets/images/google.png

  fonts:
    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo/Archivo-Thin.ttf
        - asset: assets/fonts/Archivo/Archivo-Regular.ttf
        - asset: assets/fonts/Archivo/Archivo-Medium.ttf
        - asset: assets/fonts/Archivo/Archivo-Light.ttf
        - asset: assets/fonts/Archivo/Archivo-ExtraLight.ttf
        - asset: assets/fonts/Archivo/Archivo-SemiBold.ttf
        - asset: assets/fonts/Archivo/Archivo-Bold.ttf
        - asset: assets/fonts/Archivo/Archivo-ExtraBold.ttf
